CREATE SCHEMA IF NOT EXISTS HW10S;
CREATE TABLE IF NOT EXISTS hw10s.Client
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) CHECK (LENGTH(name) BETWEEN 3 AND 200)
);
CREATE TABLE IF NOT EXISTS HW10S.Planet(
    ID VARCHAR(50) NOT NULL CHECK (ID REGEXP '^[A-Z0-9]+$'),
    name VARCHAR(200) CHECK (LENGTH(name) BETWEEN 1 AND 500)
);
CREATE TABLE IF NOT EXISTS HW10S.Ticket(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP WITH TIME ZONE,
    client_id INT,
    from_planet_id INT,
    to_planet_id INT,
    FOREIGN KEY (client_id) REFERENCES HW10S.Client(ID),
    FOREIGN KEY (from_planet_id)REFERENCES HW10S.PLANET(id)
);
ALTER TABLE HW10S.TICKET
   ADD  FOREIGN KEY (client_id)
      REFERENCES HW10S.CLIENT(id)
      ON DELETE CASCADE;
ALTER TABLE HW10S.TICKET
   ADD  FOREIGN KEY (from_planet_id)
      REFERENCES HW10S.PLANET(id)
      ON DELETE CASCADE;
ALTER TABLE HW10S.TICKET
     ADD  FOREIGN KEY (to_planet_id)
        REFERENCES HW10S.PLANET(id)
        ON DELETE CASCADE;